rootProject.name = "DistributedLocalitySchedulingTechniques"
include("lib-job")
include("impl-dedicated-queue-consumer")
include("impl-dedicated-queue-generator")
include("impl-redis-queue-consumer")
include("impl-redis-queue-generator")
include("impl-round-robin-consumer")
include("impl-round-robin-generator")
include("job-metrics")
include("internal-scheduler-test")
